feat: getAllUsersByDomain, getFieldIndex
casbin/casbin-core pull request #14
Opened 2022-07-24 13:09 UTC by Shivansh-yadav13

I will add more if this is approved
Signed-off-by: Shivansh-yadav13 <yadavshivansh@gmail.com>

2022-07-25 10:00 UTC, Shivansh-yadav13 commented
@nodece @Zxilly can you review this is part of rbac with domain

2022-07-25 15:02 UTC, nodece requested changes

2022-07-25 15:02 UTC, nodece commented on src/model/model.ts
> +    ast.fieldIndexMap = new Map();
Looks like you want to add a cache, I don't suggest you do that.

2022-07-25 15:02 UTC, nodece commented on src/model/model.ts
> +    index = -1;
A easier way:
```js
index = assertion?.tokens.findIndex((n) => n === pattern);
if (index === undefined || index === -1) {
      return -1;
}
assertion?.fieldIndexMap.set(field, index);
return index;
```

2022-07-25 15:02 UTC, nodece commented on src/enforcer.ts
> +    const index = await this.getFieldIndex('p', 'dom');
Move to line 199.

2022-07-28 02:08 UTC, hsluoyz commented
@Shivansh-yadav13

2022-07-30 04:27 UTC, Shivansh-yadav13 commented on src/enforcer.ts
> +    const index = await this.getFieldIndex('p', 'dom');
sir, which line to move 199?

2022-07-30 07:03 UTC, hsluoyz commented on src/enforcer.ts
> +    const index = await this.getFieldIndex('p', 'dom');
@nodece

2022-07-30 14:05 UTC, nodece commented on src/enforcer.ts
> +    const index = await this.getFieldIndex('p', 'dom');
203 and 204 line.

2022-07-30 14:26 UTC, hsluoyz commented
@Shivansh-yadav13 plz fix CI errors:

![image](https://user-images.githubusercontent.com/3787410/181918791-eb38dc38-8c67-4ede-9a10-43858b25c13f.png)

2022-07-31 13:20 UTC, Shivansh-yadav13 commented on src/enforcer.ts
> +    const index = await this.getFieldIndex('p', 'dom');
Fixed.

2022-07-31 15:56 UTC, nodece commented on src/model/model.ts
> +    let index = assertion?.fieldIndexMap?.get(field);
```suggestion
  
```

2022-07-31 15:56 UTC, nodece commented on src/model/model.ts
> +    index = assertion?.tokens.findIndex((n) => n === pattern);
```suggestion
    const index = assertion?.tokens.findIndex((n) => n === pattern);
```

2022-07-31 15:56 UTC, nodece commented on src/model/model.ts
> +    assertion?.fieldIndexMap?.set(field, index);
```suggestion

```

2022-07-31 15:56 UTC, nodece commented on src/model/model.ts
> +    ast.fieldIndexMap;
```suggestion

```

2022-07-31 15:56 UTC, nodece commented on src/model/assertion.ts
> +  public fieldIndexMap: Map<string, number>;
```suggestion

```

2022-07-31 15:58 UTC, nodece commented
@Shivansh-yadav13 If want to enable the cache, you need to consider removing the cache when the policy has changed.

2022-08-01 14:07 UTC, merged