feat: benchmark model
casbin/casbin-core pull request #4
Opened 2022-06-16 13:18 UTC by Shivansh-yadav13

- Demo PR (WIP)
- added benchmarks for model
- test/benchmark/model.ts

2022-06-16 14:21 UTC, nodece requested changes
Good work, could you add a workflow for the benchmark?

2022-06-16 14:21 UTC, nodece commented on package.json
> +    "benny": "^3.7.1",
Move this to `devDependencies`.

2022-06-17 09:36 UTC, Shivansh-yadav13 commented
> Good work, could you add a workflow for the benchmark?

@nodece pls review, it will save a result file for each suite. eg: `test/benchmark/results/RBACModel.json`

2022-06-17 16:09 UTC, nodece commented
By the way, you should use `test` instead of `feat`, so like `test: add benchmark for model`.

2022-06-17 16:10 UTC, nodece approved these changes

2022-06-18 09:31 UTC, nodece commented
Please check CI.

2022-06-19 10:34 UTC, nodece commented
It looks like you updated other dependencies in yarn.lock file, please rollback the package.json and yarn.lock, then add benny by `yarn add benny -D` command.

2022-06-20 12:57 UTC, Shivansh-yadav13 commented
I have fixed the CI

2022-06-20 14:49 UTC, nodece approved these changes

2022-06-20 14:49 UTC, merged